name: Build

on:
  push:
    branches: [ master ]

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Install deps
        run: sudo apt-get install -y mingw-w64 build-essential

      - name: Build
        run: make build-all

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "[CI] Rebuild native files"
          body: Automated changes by CI pipeline.
          commit-message: "[CI] Rebuild native files"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          sign-commits: true
          branch: ci/rebuild
          add-paths: '*.syso'
